### ISSUE TITLE
`xctrls:codeeditor` port from CodeMirror to ACE needs to be completed

### ISSUE THREAD

**Issue by idearat** [TechnicalPursuit/TIBET#390]
'- [ ] The functionality that allows the JSON formatter to be called from outside of the editor.
- [ ] The rest of the methods that were 'stubbed' but not completely ported.

**Comment by bedney** [comment]
We're deprecating the `xctrls:codeeditor` object and replacing it with `xctrls:editor` (which is based on the much better CodeMirror 6). Closing this as `xctrls:codeeditor` will be removed at some point.
