### ISSUE TITLE
trait resolution of APP.sherpa.ComputedTag etc. requires "immediateMode"... but breaks a lot of others

### ISSUE THREAD

**Issue by idearat** [TechnicalPursuit/TIBET#532]
The trait resolution logic needs more tests to understand why we had to set immediateMode for sherpa root tags that have traits... which then get more traits.... while setting immediateMode to true by default causes multiple crashes on startup.

**Comment by bedney** [comment]
We now resolve super type 'trait chains' dynamically as the system loads for proper lookup. We should remove the 'immediate' flag as it's no longer necessary.
